language: node_js
node_js:
- 12
script:
- yarn build
addons:
  ssh_known_hosts: 134.209.31.56
before_install:
- openssl aes-256-cbc -K $encrypted_e8c214013cf0_key -iv $encrypted_e8c214013cf0_iv
  -in deploy_rsa.pub.enc -out ./ssh/deploy_rsa.pub -d
- mkdir ./ssh
- eval "$(ssh-agent -s)"
- chmod 600 ./ssh/deploy_rsa.pub
- ssh-add ./ssh/deploy_rsa.pub
deploy:
  provider: script
  script: rsync -r --delete-after --quiet $TRAVIS_BUILD_DIR/build duvarboun@134.209.31.56:/home/duvarboun/karacabot/build
    && ssh duvarboun@134.209.31.56 "cd karacabot && yarn install"
  on:
    branch: deploy
